# Generated by Django 2.0.7 on 2019-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20190315_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
